### ISSUE TITLE
Failed to refresh Rclone VFS

### ISSUE THREAD

**Issue by Haldir31** [Pukabyte/blackhole-UD#2]
Hello,

I have an error with rclone refresh task with the following message:
``Failed to refresh Rclone VFS for /Import/radarr/completed: HTTPConnectionPool(host='localhost', port=13917): Max retries exceeded with url: /vfs/refresh?dir=%2FImport%2Fradarr%2Fcompleted (Caused by NewCiled to establish a new connection: [Errno 111] Connection refused'))``

My setup has protected rclone endpoint so i have updated the config file for vfs parameter as: 
``vfs_url = http://_Username_:_Password_@localhost:13917``

Using a manual refresh from rclone, i don't get error to connect to the endpoint:
```
rclone rc --url Username:Password@localhost:13917  vfs/refresh dir='/Import/radarr/completed' recursive=true
{
        "result": {
                "/Import/radarr/completed": "OK"
        }
}
```

**Comment by Pukabyte** [comment]
Is rclone running on host?
if so, update your config to this:
`vfs_url = http://172.19.0.1:5574`

where 172.19.01 needs to be the docker gateway ip and 5574 is the rclone port.

Let me know how that works for you.

I do think, however, the vfs refresh might be obsolete now as UD is doing a fresh on its self when it detects an nzb

**Comment by Haldir31** [comment]
Thanks for the tip. I have updated the remote by the public IP for rclone and other apps and don't get anymore error to refresh rclone. (hosted on whatbox)
